// ============================================================================
// Datos mock del catálogo - basados en el prototipo HTML original
// ============================================================================

export const mockProducts = [
  {
    id: 1,
    name: 'Bocadillo de jamón',
    description: 'Pan artesano con jamón serrano',
    price: 2.5,
    category: 'bocadillos',
    emoji: '🥪',
    allergens: ['gluten'],
    available: true,
    stock: 24,
  },
  {
    id: 2,
    name: 'Bocadillo de tortilla',
    description: 'Pan con tortilla francesa recién hecha',
    price: 2.2,
    category: 'bocadillos',
    emoji: '🥖',
    allergens: ['gluten', 'huevo'],
    available: true,
    stock: 18,
  },
  {
    id: 3,
    name: 'Bocadillo de queso',
    description: 'Pan con queso manchego',
    price: 2.3,
    category: 'bocadillos',
    emoji: '🧀',
    allergens: ['gluten', 'lacteos'],
    available: true,
    stock: 20,
  },
  {
    id: 4,
    name: 'Pizza margarita',
    description: 'Porción individual de pizza casera',
    price: 2.8,
    category: 'comida',
    emoji: '🍕',
    allergens: ['gluten', 'lacteos'],
    available: true,
    stock: 15,
  },
  {
    id: 5,
    name: 'Empanadilla de atún',
    description: 'Empanadilla casera rellena de atún',
    price: 1.8,
    category: 'comida',
    emoji: '🥟',
    allergens: ['gluten', 'pescado', 'huevo'],
    available: true,
    stock: 22,
  },
  {
    id: 6,
    name: 'Zumo de naranja',
    description: 'Recién exprimido (200ml)',
    price: 1.5,
    category: 'bebidas',
    emoji: '🍊',
    allergens: [],
    available: true,
    stock: 30,
  },
  {
    id: 7,
    name: 'Agua mineral',
    description: 'Botella de 500ml',
    price: 0.8,
    category: 'bebidas',
    emoji: '💧',
    allergens: [],
    available: true,
    stock: 50,
  },
  {
    id: 8,
    name: 'Refresco',
    description: 'Cola, naranja o limón (330ml)',
    price: 1.5,
    category: 'bebidas',
    emoji: '🥤',
    allergens: [],
    available: true,
    stock: 35,
  },
  {
    id: 9,
    name: 'Donut de chocolate',
    description: 'Donut glaseado con cobertura',
    price: 1.2,
    category: 'dulces',
    emoji: '🍩',
    allergens: ['gluten', 'lacteos', 'huevo'],
    available: true,
    stock: 16,
  },
  {
    id: 10,
    name: 'Galletas con pepitas',
    description: 'Pack de 3 galletas con pepitas de chocolate',
    price: 1.0,
    category: 'dulces',
    emoji: '🍪',
    allergens: ['gluten', 'lacteos', 'huevo'],
    available: true,
    stock: 28,
  },
];

export const mockCategories = [
  { id: 'todos', name: 'Todos', emoji: '🍽️' },
  { id: 'bocadillos', name: 'Bocadillos', emoji: '🥪' },
  { id: 'comida', name: 'Comida', emoji: '🍕' },
  { id: 'bebidas', name: 'Bebidas', emoji: '🥤' },
  { id: 'dulces', name: 'Dulces', emoji: '🍩' },
];

export const allergenLabels = {
  gluten: 'Gluten',
  lacteos: 'Lácteos',
  huevo: 'Huevo',
  pescado: 'Pescado',
  frutos_secos: 'Frutos secos',
  soja: 'Soja',
};
